image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build & Run Container
    init: docker build -t whiskeyapi .
    command: |
      gp sync-done dockerrun
      docker run -d -p 8000:3000 --name whiskeyapi whiskeyapi
  - name: Open Swagger
    command: |
      gp sync-await dockerrun
      gp preview $(gp url 8000)/swagger/index.html
  - name: Terraform
    init: |
      brew tap hashicorp/tap
      brew install hashicorp/tap/terraform
    command: |
      gp sync-await waitonazurecli
      cd  terraform
      terraform init
      terraform fmt
      terraform validate
      terraform plan
  - name: Azure CLI
    init: |
      brew update && brew install azure-cli
    command: |
      az login --use-device-code
      az account set --subscription "datagriff Teaching"
      az account show
      gp sync-done waitonazurecli
      

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-dotnettools.csharp
    - ms-azuretools.vscode-docker
    - hashicorp.terraform