image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      cd WhiskeyAPI
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-dotnettools.csharp
    - ms-azuretools.vscode-docker