image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build Image
    init: docker build -t whiskeyapi .
  - name: Run Container
    command: docker run -d -p 8000:3000 --name whiskeyapi whiskeyapi
  - name: Open Swagger
    command: gp preview $(gp url 8000)/swagger/index.html 

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-dotnettools.csharp
    - ms-azuretools.vscode-docker